// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_skilled_slayer = "CgkIyv7ajoYeEAIQDA"; // <GPGSID>
        public const string achievement_master_farmer = "CgkIyv7ajoYeEAIQCw"; // <GPGSID>
        public const string achievement_skilled_miner = "CgkIyv7ajoYeEAIQAA"; // <GPGSID>
        public const string achievement_professional_slayer = "CgkIyv7ajoYeEAIQDQ"; // <GPGSID>
        public const string leaderboard_cutting_level = "CgkIyv7ajoYeEAIQEg"; // <GPGSID>
        public const string achievement_professional_miner = "CgkIyv7ajoYeEAIQAQ"; // <GPGSID>
        public const string achievement_consumer = "CgkIyv7ajoYeEAIQGg"; // <GPGSID>
        public const string leaderboard_mining_level = "CgkIyv7ajoYeEAIQEw"; // <GPGSID>
        public const string achievement_pack_rat = "CgkIyv7ajoYeEAIQHg"; // <GPGSID>
        public const string achievement_skilled_digger = "CgkIyv7ajoYeEAIQAw"; // <GPGSID>
        public const string leaderboard_fishing_level = "CgkIyv7ajoYeEAIQFw"; // <GPGSID>
        public const string achievement_super_summoner = "CgkIyv7ajoYeEAIQHQ"; // <GPGSID>
        public const string achievement_skilled_farmer = "CgkIyv7ajoYeEAIQCQ"; // <GPGSID>
        public const string achievement_professional_farmer = "CgkIyv7ajoYeEAIQCg"; // <GPGSID>
        public const string leaderboard_slaying_level = "CgkIyv7ajoYeEAIQFg"; // <GPGSID>
        public const string achievement_master_slayer = "CgkIyv7ajoYeEAIQDg"; // <GPGSID>
        public const string achievement_master_cutter = "CgkIyv7ajoYeEAIQCA"; // <GPGSID>
        public const string leaderboard_farming_level = "CgkIyv7ajoYeEAIQFQ"; // <GPGSID>
        public const string achievement_dungeon_raider = "CgkIyv7ajoYeEAIQIA"; // <GPGSID>
        public const string achievement_patron = "CgkIyv7ajoYeEAIQGQ"; // <GPGSID>
        public const string achievement_mega_buyer = "CgkIyv7ajoYeEAIQGw"; // <GPGSID>
        public const string achievement_skilled_fisher = "CgkIyv7ajoYeEAIQDw"; // <GPGSID>
        public const string achievement_master_miner = "CgkIyv7ajoYeEAIQAg"; // <GPGSID>
        public const string achievement_skilled_cutter = "CgkIyv7ajoYeEAIQBg"; // <GPGSID>
        public const string leaderboard_digging_level = "CgkIyv7ajoYeEAIQFA"; // <GPGSID>
        public const string achievement_professional_cutter = "CgkIyv7ajoYeEAIQBw"; // <GPGSID>
        public const string achievement_master_digger = "CgkIyv7ajoYeEAIQBQ"; // <GPGSID>
        public const string achievement_home_sweet_home = "CgkIyv7ajoYeEAIQHw"; // <GPGSID>
        public const string achievement_professional_digger = "CgkIyv7ajoYeEAIQBA"; // <GPGSID>
        public const string achievement_master_fisher = "CgkIyv7ajoYeEAIQEQ"; // <GPGSID>
        public const string achievement_bringing_the_goods = "CgkIyv7ajoYeEAIQHA"; // <GPGSID>
        public const string achievement_professional_fisher = "CgkIyv7ajoYeEAIQEA"; // <GPGSID>

}

